### ISSUE TITLE
Keypad component broken: Polymer removed from Home Assistant

### ISSUE THREAD

**Issue by vincentdh** [Dilbert66/esphome-dsckeybus#102]
The Polymer library has been removed from home-assistant and broke the alarm-keypard-card component.

The component have to be rewrite using Lit or plain JS.

If you didn't start the migration yet, I can do it and open a PR.

**Comment by Dilbert66** [comment]
Already done in dev branch

**Comment by vincentdh** [comment]
Jeez ...  I'm blind!

I've pull the dev branch, but didn't update the JS loaded by lovelace 🤦🏼‍♂️
