### ISSUE TITLE
timer0 was not declared

### ISSUE THREAD

**Issue by dharampaul** [Dilbert66/esphome-dsckeybus#105]
Hi Dilbert, 
The following error was thrown using nodemcu ESP8266 board:
******
Compiling .pioenvs\dscalarm\src\esphome\components\api\api_pb2.cpp.o
src\dscKeybusInterface.cpp: In static member function 'static void dscKeybusInterface::dscDataInterrupt()':
src\dscKeybusInterface.cpp:667:13: error: 'timer0' was not declared in this scope; did you mean 'time'?
  667 |   timerStop(timer0);
      |             ^~~~~~
      |             time
src\dscKeybusInterface.cpp:667:3: error: 'timerStop' was not declared in this scope; did you mean 'timer_t'?
  667 |   timerStop(timer0);
      |   ^~~~~~~~~
      |   timer_t
src\dscKeybusInterface.cpp:668:23: error: 'timer0Mux' was not declared in this scope
  668 |   portENTER_CRITICAL(&timer0Mux);
      |                       ^~~~~~~~~
src\dscKeybusInterface.cpp:668:3: error: 'portENTER_CRITICAL' was not declared in this scope
  668 |   portENTER_CRITICAL(&timer0Mux);
      |   ^~~~~~~~~~~~~~~~~~
*** [.pioenvs\dscalarm\src\dscKeybusInterface.cpp.o] Error 1
*******************
I used correct board type in yaml file:
esphome:
  name: $systemName
  platform: ESP8266
  board: nodemcuv2
Shall be thankful for any input.
Dharam

**Comment by Dilbert66** [comment]
Should be fixed now
