### ISSUE TITLE
Component Debug error

### ISSUE THREAD

**Issue by feradelectronics** [Dilbert66/esphome-dsckeybus#106]
Tried copying the new simplified yaml as you provided.  How can i fix this.  I also installed the new dscKeybusInterface folder as needed.

I get the following error:
text_sensor.debug: [source /config/esphome/dscalarmesp.yaml:333]
  
  Component text_sensor.debug requires component debug.
  platform: debug
  device: 
    name: Device Info

Thanks in advance for your quick response to resolving this issue.

**Comment by Dilbert66** [comment]
Comment out with a # sign these 3 lines in the yaml:

- platform: debug
 device:
   name: "Device Info"

**Comment by feradelectronics** [comment]
I am using an esp32

**Comment by Dilbert66** [comment]
delete or comment them out anyhow.  They are not needed.
