### ISSUE TITLE
DSCKeybus keypad control no longer working

### ISSUE THREAD

**Issue by feradelectronics** [Dilbert66/esphome-dsckeybus#108]
Since the last dev updates after creating short yaml configuration the DSCKeybus keypad is not working reliably.  Cannot arm because system reports unknown.  I can manually arm system from DSC keypad.  DSCKeybus then reports system armed as expected.  I can then disarm system with DSCKeybus.  Seems that communication is ok.  Please let me know how to resolve this.

**Comment by Dilbert66** [comment]
I need to see logs and config.  I can't guess as it works fine here.

**Comment by feradelectronics** [comment]
Thanks in advance.

 



 ***@***.***> Scott Fritzler C.E.T.

 <https://ferad.com/> FERAD Electronics Inc.

B, 12736 St. Albert Trail NW

Edmonton, Alberta, T5L 4S5

Phone: 587-773-3333 or 780-628-3649

Toll Free: 1855-53-FERAD (1855-533-3723)

**Comment by feradelectronics** [comment]
[logs_dscalarm_logs.zip](https://github.com/Dilbert66/esphome-dsckeybus/files/13444312/logs_dscalarm_logs.zip)
here are the files

**Comment by Dilbert66** [comment]
The dev version will not work with the yaml you are using now.  Everthing has been converted to external components.  You need to convert your setup to the new yaml format and recompile. You do not need to download any code anymore. Just the yaml itself. As to why it's not arming, I can't see anything in the logs as the command is not even getting to the panel from what I see.  The disarm cmd is there though.

**Comment by feradelectronics** [comment]
i will try and confirm. thanks.

**Comment by Dilbert66** [comment]
The system unknown error indicates a possible config issue with the keypad card itself and not the esphome component.  Let me know how you send your arming cmd normally.

**Comment by feradelectronics** [comment]
I reprogrammed with the new dscalarm.yaml and configured as needed.  Thanks,.
Regarding the HA Alarm panel, still displays the same as originally mentioned above.  This is the standard alarm panel with HA.  Do i need to use the DSCKeybus alarm panel instead?

**Comment by Dilbert66** [comment]
You do not need to change anything on the HA panel itself. That works with all code.

**Comment by Dilbert66** [comment]
Good point! I will do that. Thanks!
