### ISSUE TITLE
Feature Request - Zone Names

### ISSUE THREAD

**Issue by tiaanv** [Dilbert66/esphome-dsckeybus#119]
Awesome work.  Been using your component for a long time, and following all the updates, and improvements.

At the moment, if you look at the two main text sensors (that are used to populate the virtual keypad), then the one slight difference is that it is of course not able to show the zone names when looking at open zones etc.  
![image](https://github.com/Dilbert66/esphome-dsckeybus/assets/4703398/3b38c8dd-2c49-48bc-a860-7e7bace6814a)

I do understand this.

I took a brief look at the code, and could not find a clear place where this text is generated.  I have a limited understanding at the moment of how it all hangs together.  I was wondering if it would be possible to retrieve the actual zone names from the yaml config of zones, and use the name, as configured in yaml

![image](https://github.com/Dilbert66/esphome-dsckeybus/assets/4703398/679dab32-9afa-48f1-b5f4-9b2e5cf7cdc7)

I am happy to look into this, and potentially contribute the code after some development effort, but would appreciate some initial guidance.

**Comment by Dilbert66** [comment]
Good idea, I will add the feature to the dev branch.

**Comment by tiaanv** [comment]
If I am not mistaken, then the actual change will be in the https://github.com/Dilbert66/esphome-components repo?

**Comment by Dilbert66** [comment]
Yes, the change will be in the components repo in dev branch.  Just use this source line under the "external_components" section

- source: github://Dilbert66/esphome-components@dev

**Comment by tiaanv** [comment]
Schweet.... FAST man...
Will give it a dry run and let you know.

**Comment by tiaanv** [comment]
![image](https://github.com/Dilbert66/esphome-dsckeybus/assets/4703398/ea54edc2-5aca-4313-8620-2a895fb92167)
Happy dance!

**Comment by tiaanv** [comment]
I haven't checked what impact this change (if any) will have on if you try to use the Bypass zone menus etc. 
From a front en perspective it works.  
![image](https://github.com/Dilbert66/esphome-dsckeybus/assets/4703398/80929157-06bf-40a6-9406-04e5b3ed3c07)

I will verify on the actual alarm panel and see

**Comment by Dilbert66** [comment]
Ya, the interface needs tweeking for a more pleasing display depending on the zone name lenghts.  Won't impact operation.

**Comment by tiaanv** [comment]
I think this 100% satisfies my request.  I will look out for merge into main, then change back eventually.  Sidenote.  Let me know if you need any experimental stuff tested.

**Comment by Dilbert66** [comment]
Good stuff! Sure, I'll merge to main soon enough. Tks for the offer on testing! Much appreciated.
I'm working on a few other components unrelated to the panel right now.  One is a telegram bot running totally on the esp  which includes notification and responding to telegram cmds.

**Comment by tiaanv** [comment]
Interesting.  Curious as the application of running Telegram bot on ESP vs just implementing it on HA.

**Comment by Dilbert66** [comment]
The concept is for using the ESPhome device completely standalone without a controlling server such as HA.  Let's say you want to give friends, parents access to having a virtual keypad, monitoring of their alarm system without having to also install a whole home monitoring system.  With the ESP having a web interface with the virtual keypad, the bot for notification of events, etc, it provides most of the needed features.  A telegram bot with remote command capability is handy for managing the alarm outside the home network.  I have something similar runngin with an arduino implementation but the code was cumbersome, so trying it out with the ESPhome platform

**Comment by tiaanv** [comment]
Makes sense. Happy to play around with it and give you some feedback
