### ISSUE TITLE
dsckeybus Fault 

### ISSUE THREAD

**Issue by thunderwood19** [Dilbert66/esphome-dsckeybus#12]
After hooking everything up, I am currently getting a keybus fault error on the main alarm panel and am unable to use the Alarm system.

**Comment by Dilbert66** [comment]
This would be a problem with your wiring.  Bad ground, etc.

**Comment by thunderwood19** [comment]
I believe that to be the issue aswell, just can't seem to diagnose the point of failure. Grounds are all tied, wiring diagram was followed to the t. 
![16081659101799160145274091206960](https://user-images.githubusercontent.com/66544095/102423526-da1bcd00-3fce-11eb-92b6-65e05d92e9d5.jpg)

**Comment by Dilbert66** [comment]
transistor pinout correct? Correct values for resistors? etc.  Something is shorting one of the lines or a bad ground, those are the only possibilities as far as I can see.

**Comment by thunderwood19** [comment]
Just got into wiring, but resistors are simple enough. I think I got the transistor correct : 
![1608168889197532740925601195787](https://user-images.githubusercontent.com/66544095/102426885-da6b9680-3fd5-11eb-897b-381d93a46f96.jpg)

Left: to green wire
Center: to 1k resistor and then do
Right: to ground 
Transistor is a 2222a

**Comment by Dilbert66** [comment]
e b c.  E=ground,b=1k, c=green wire. I think you have e and c backwards.

**Comment by thunderwood19** [comment]
Ok, so that was a problem. Switched the ends around and now it seems im a little further along. The issue now is that the alarm system only works when the black wire is not connected to the nodemcu

**Comment by thunderwood19** [comment]
Re did wiring on a new board:
![20201216_210831](https://user-images.githubusercontent.com/66544095/102439683-4ce37300-3fe4-11eb-830c-203914be6b8f.jpg)
Left to nodemcu, riright to alarm panel. 

Connected to panel:
![16081751680137794887259337777401](https://user-images.githubusercontent.com/66544095/102439752-743a4000-3fe4-11eb-879a-3371ebe24a60.jpg)

Wires to ground bundled and then connected to other grounds on panel. 

Panel is currently spazzing out and sensors aren't responding.  Nodemcu was flashed with latest and zones were configured prior in the yaml.

**Comment by Dilbert66** [comment]
You still have a wiring issue somewhere.

**Comment by thunderwood19** [comment]
Resistors are all showing as their proper values (10kohms,  33kohms, and 1kohms). The following are the Resistors im using. 
![20201217_075159](https://user-images.githubusercontent.com/66544095/102497225-002c8600-403e-11eb-88bf-e0c89afed01c.jpg)

**Comment by Dilbert66** [comment]
Well, I don't have any other suggestion. It's still a wiring issue somewhere.

**Comment by Dilbert66** [comment]
One part that does not make sense in your wiring is this resistor?  The nodemcu ground should be direct to the panel ground. No resistor in between.
![image](https://user-images.githubusercontent.com/7193213/102508694-b3ec4080-4053-11eb-9b01-ef21b14b7c0b.png)

**Comment by Dilbert66** [comment]
I don't see the 1k resistor between the nodemcu and the transistor base.

**Comment by thunderwood19** [comment]
The misplaced 1k resistor was it. I really appreciate your help with troubleshooting this as I learned alot from this experience. Keep doing amazing work!

**Comment by Dilbert66** [comment]
Good stuff! Have fun!
