### ISSUE TITLE
DSCkeybus API call from lambda

### ISSUE THREAD

**Issue by chreggy** [Dilbert66/esphome-dsckeybus#121]
Hello,

I tested last year this projet with success but with the last sources, how can I convert this lambda API calls ?

- lambda: 'static_cast< DSCkeybushome*> (id(dsckeybus).get_component(0))->set_alarm_state("A","",1);'
- lambda: 'static_cast< DSCkeybushome*> (id(dsckeybus).get_component(0))->set_alarm_state("D","$accessCode",1);'

Best Regards.

**Comment by Dilbert66** [comment]
Just use "set_alarm_state("D","$accessCode",1):" on it's own.
