### ISSUE TITLE
Partition 1 Status Unavailable

### ISSUE THREAD

**Issue by seanco1** [Dilbert66/esphome-dsckeybus#125]
I seem to have an issue with my "Partition 1 Status". This value returns "unavailable" when "Partition 1 Ready" state is off. The same thing happens with partition 2

This is from the YAML file.
  - platform: template
    id_code: ps_1  
    name: "Partition 1 Status"
    icon: "mdi:shield"

  - platform: template
    id_code: ps_2  
    name: "Partition 2 Status" 
    icon: "mdi:shield" 

![Capture](https://github.com/Dilbert66/esphome-dsckeybus/assets/68070582/c678795e-a41c-4615-a778-104227119eb9)

We should be receiving status like "disarmed, armed_away, armed_home, triggered". The example above at 7:34 should be triggered and the later one was just general movement in the area

**Comment by Dilbert66** [comment]
That is normal.  Unavailable means the partition is not ready. ie, has open/active zones so can't be armed.    Disarmed is when the panel is not armed and has no open zones.  Triggered only shows when the alarm is on and a zone opens.

**Comment by Dilbert66** [comment]
I've modified the dev branch code to now indicate "not-ready"
