### ISSUE TITLE
Mosfet level converter circuit is wrong

### ISSUE THREAD

**Issue by go2net** [Dilbert66/esphome-dsckeybus#142]
You should switch the drain and source connections for proper operation. The high-level (12V logic) pin should be connected to the drain (D) pin, and the low-level (3.3V logic) pin should be connected to the source (S) pin.

**Comment by Dilbert66** [comment]
The mosfet convert drawing is correct. High level to Source and low level to Drain.
https://circuitdigest.com/tutorial/bi-directional-logic-level-controller-using-mosfet

**Comment by Dilbert66** [comment]
Ok, I'm confused here.  What drawiing are you looking at? That's what I have.  High side to drain and low side to to source?

**Comment by go2net** [comment]
I may have submitted to the wrong repository. After checking again, I couldn't find the MOSFET converter circuit. Let me verify if I need to submit it to another repository.

**Comment by go2net** [comment]
The link (https://github.com/Dilbert66/esphome-dsckeybus/tree/dev) is still under your repository which have a wrong schematic, but it's on the dev branch, not the master branch. Google directed me to your dev branch.

**Comment by go2net** [comment]
Not an issue with original circuit. it was just too small, and I misread it.
