### ISSUE TITLE
Can dsckeybus be used as a master to troubleshoot keyboards and modules

### ISSUE THREAD

**Issue by rkgladney** [Dilbert66/esphome-dsckeybus#20]
I am interested in using an Arduino or an esp8266 as a master controller for troubleshooting PK5501 keyboards or DSC expansion modules without having a PC1832 or PC1616 attached.  Reading through your readme information, it appears that this might be possible.  Do you have an Arduino example file already generated that I can use as a starting point, and are there limitations to doing this that I am not aware of at this point?  I do not have a spare PC1832 for troubleshooting, but I do have an abundance of Arduino uno and esp8266 modules at my disposal.

**Comment by Dilbert66** [comment]
See this project here: https://github.com/taligentx/dscKeybusInterface
Taligentx has implemented code to make the device as a master.  There is no support to debug expansion modules at this time.
