### ISSUE TITLE
HA fails to connect to alarm

### ISSUE THREAD

**Issue by tatkinsza** [Dilbert66/esphome-dsckeybus#62]
I am unable to connect the ESP8266 to HA. The device stays gray in ESP home on the ESP home page. PReviosuly (about a year ago), I did have this all working, but I have put HA on a new Rasp Pi and reflashed the ESP. Any suggestions where I can check. Could the ESP be faulty - anyway of checking that (It does connect to my wifi happily)

**Comment by Dilbert66** [comment]
Remove and re-add the device from the esphome integration.  Also have a look at the device logs for hints.

**Comment by tatkinsza** [comment]
Going to close asI think its a problem on the alarm or the esp8266
