### ISSUE TITLE
ESP firmware 

### ISSUE THREAD

**Issue by paljanos56** [Dilbert66/esphome-dsckeybus#7]
I have read carefully your comments, but I dont know what firmware shall I load to Wemos D1?  Do I use the original (Taligent) files? It was written for MQTT connection!  Or where can I find the program to upload, and with which IDE must use? Thanks forward!

**Comment by Dilbert66** [comment]
It's designed for the Esphome system on https://esphome.io/. You need to copy both the  dscalarm.yaml and the subdirectory "dscKeybusInterface" into your main esphome directory on home assistant.

**Comment by paljanos56** [comment]
Thanks for fast response . I will do it!
