### ISSUE TITLE
using with another alarm?

### ISSUE THREAD

**Issue by emilianos** [Dilbert66/esphome-dsckeybus#88]
Is there any way to check if the library will work with my C&K systems System 236?

**Comment by Dilbert66** [comment]
No, it needs to be a DSC power832 system.

**Comment by jjmbonzo** [comment]
Does this scripts under EspHome in HA works for DSC Classic PC1550 version? thanks

**Comment by Dilbert66** [comment]
No it does not.  Only DSC Power series.
