### ISSUE TITLE
ESPHome Compiling Error

### ISSUE THREAD

**Issue by 1gnwld** [Dilbert66/esphome-dsckeybus#89]
Getting the following error when trying to compile in ESPHome. I have downloaded the files from your GitHub repo and uploaded directly into HA. This is the dev version of files. 

INFO ESPHome 2023.5.5
INFO Reading configuration /config/esphome/DscAlarm.yaml...
WARNING GPIO12 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Detected timezone 'America/Chicago'
INFO Generating C++ source...
INFO Compiling app...
Processing dscalarm (board: nodemcu-32s; framework: arduino; platform: platformio/espressif32@5.3.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- WiFi @ 2.0.0
|-- ESPmDNS @ 2.0.0
Compiling /data/dscalarm/.pioenvs/dscalarm/src/main.cpp.o
Compiling /data/dscalarm/.pioenvs/dscalarm/lib64d/WiFi/WiFiClient.cpp.o
In file included from src/main.cpp:73:
src/dscAlarm.h:201:44: error: expected class-name before ',' token
 class DSCkeybushome: public CustomAPIDevice, public RealTimeClock {
                                            ^
src/dscAlarm.h: In member function 'virtual void DSCkeybushome::setup()':
src/dscAlarm.h:397:5: error: 'register_service' was not declared in this scope
     register_service( & DSCkeybushome::set_alarm_state, "set_alarm_state", {
     ^~~~~~~~~~~~~~~~
src/dscAlarm.h:397:5: note: suggested alternative: 'register_t'
     register_service( & DSCkeybushome::set_alarm_state, "set_alarm_state", {
     ^~~~~~~~~~~~~~~~
     register_t
Compiling /data/dscalarm/.pioenvs/dscalarm/lib64d/WiFi/WiFiGeneric.cpp.o
*** [/data/dscalarm/.pioenvs/dscalarm/src/main.cpp.o] Error 1
========================== [FAILED] Took 3.97 seconds ==========================

**Comment by Dilbert66** [comment]
Ensure you have this section in your yaml:
```
time:
 - platform: sntp
   id: sntp_time 
```

**Comment by 1gnwld** [comment]
I double checked dscalarm.yaml and I do have that entry. 
I added my yaml file with the password removed. Am I missing something here?
[dscalarm.txt](https://github.com/Dilbert66/esphome-dsckeybus/files/11653493/dscalarm.txt)

**Comment by Dilbert66** [comment]
You have commented the "api:" line. That is necessary. Either mqtt or api.

**Comment by 1gnwld** [comment]
DANG IT!!
You are right on the money! IT WORKS!!!
Thank you!!!
