### ISSUE TITLE
Connection Issue?

### ISSUE THREAD

**Issue by feradelectronics** [Dilbert66/esphome-dsckeybus#95]
I have been using Dev branch successfully with 8266 non-isolated installation with DSC Power864.  Latest version installed.
Tried upgrading to ESP32 isolated connection using 810 optos.  Cannot get values from DSC panel as expected.  
Attached is log file of status and config.  Also any help optimizing configuration files greatly appreciated.

Thanks in advance for any help resolving this issue asap.
[DSC ESP32 Log.txt](https://github.com/Dilbert66/esphome-dsckeybus/files/12053266/DSC.ESP32.Log.txt)
[dscalarmesp.yaml.txt](https://github.com/Dilbert66/esphome-dsckeybus/files/12053311/dscalarmesp.yaml.txt)

**Comment by Dilbert66** [comment]
I just see garbage data in the logs so you have a connection issue, bad signal or reversed lines somewhere.
