### ISSUE TITLE
misleading documentation

### ISSUE THREAD

**Issue by fede843** [Dilbert66/esphome-dsckeybus#97]
Hi, I have been fighting against the lovelace panel for a while. I was following instructions as per documentation here, and finally could realise where the issue was. It is fairly obvious now, but nevertheless I think you should update the main doc.

You say:

    ... add a new resource in your lovelace configuration pointing to /local/alarm-panel-card.js?id=1 ...

but in fact there is no "alarm-panel-card.js". It is indeed "alarm-keypad-card.js". I know, I know, I should have realised before, but nevertheless there is a mismatch in name convention here.

**Comment by Dilbert66** [comment]
Ahh, ok, I'll take care of that. Tks for pointing it out. Yes, that would cause confusion
