### ISSUE TITLE
Partition Status Unavailable

### ISSUE THREAD

**Issue by meneerfrikkie** [Dilbert66/esphome-dsckeybus#99]
Hi everyone, thank you to the Dilbert66 for the amazing work, has anyone come across the partition status where it is unavailable, could they please assisting, Many Thanks!
<img width="784" alt="Screenshot 2023-08-11 at 21 53 36" src="https://github.com/Dilbert66/esphome-dsckeybus/assets/100700962/ca33fe96-9900-45bb-b7d4-ec69e8fdd504">

**Comment by tiaanv** [comment]
I get the same.  Did you manage to figure it out?

**Comment by Dilbert66** [comment]
It means that the partition is not ready. You can change it to be "Not Ready" in line 98 of dscalarm.h
```
const char STATUS_NOT_READY[] PROGMEM = "unavailable"; //ha alarm panel likes to see "unavailable" instead of not_ready when the system can't be armed
```

**Comment by Dilbert66** [comment]
I've modified the code to show "not_ready" instead.
